package main

type MachineID uint8

type ClusterClient interface {
	// Register Service Job.
	// Params:
	//   • throughput
	//   • softLimit
	//   • hardLimit
	// Returns:
	//   • Address and Port

	// Register Batch Job
	// Params:
	//   • Duration
	//   • CPU requirement
	//   • Service's Address
	// Returns:
	//   • 200 OK
}

type SimVisualization interface {
	NewMachineCallback() func(name string)

	NewMachine(name string)
	// The return value is the stream of throughputs generated by this service.
	AddService(machine string, throughput, softLimit, hardLimit uint64) <-chan uint64
	AddNeighbor(machine string, cpuReq uint8)
}
